/* eslint-disable */
(() => {
  window.__BLOG_POSTS__ = [
    {
      id: "software-design-patterns-cheatsheet",
      href: "posts/software-design-patterns-cheatsheet.html",
      title: "软件设计师设计模式速查：23种模式一张地图",
      date: "2026-09-22",
      updated: "2026-09-22",
      category: "学习札记",
      excerpt: "用大白话整理软件设计师常考的23种经典设计模式，覆盖创建型、结构型、行为型，以及适配器、工厂、观察者、策略等高频辨析。",
      tags: ["软件设计师", "设计模式", "软考", "工厂模式", "适配器模式", "观察者模式"],
      words: 4200,
      readTime: 12,
    },
    {
      id: "week10-pytorch-tensor-autograd-review",
      href: "posts/week10-pytorch-tensor-autograd-review.html",
      title: "第十周学习复盘：从张量到自动求导",
      date: "2026-09-21",
      updated: "2026-09-21",
      category: "学习札记",
      excerpt: "开始学习《动手学深度学习》，通过PyTorch张量、广播、数据预处理、线性代数和自动求导打牢基础。",
      tags: ["Python", "PyTorch", "深度学习", "张量", "自动求导", "梯度", "周报"],
      words: 3300,
      readTime: 10,
    },
    {
      id: "week9-association-analysis-fp-growth-review",
      href: "posts/week9-association-analysis-fp-growth-review.html",
      title: "第九周学习复盘：从购物篮中寻找关联规则",
      date: "2026-09-14",
      updated: "2026-09-14",
      category: "学习札记",
      excerpt: "复现Apriori和FP-growth，从支持度、置信度、频繁项集到FP树与条件模式基，理解关联分析的两条实现路线。",
      tags: ["Python", "机器学习", "Apriori", "FP-growth", "关联分析", "频繁项集", "周报"],
      words: 3500,
      readTime: 11,
    },
    {
      id: "week8-kmeans-clustering-learning-review",
      href: "posts/week8-kmeans-clustering-learning-review.html",
      title: "第八周学习复盘：从一堆点到几个簇",
      date: "2026-09-07",
      updated: "2026-09-07",
      category: "学习札记",
      excerpt: "复现标准K均值、二分K均值和地图地点聚类，用真实结果理解簇、质心、SSE与随机初始化。",
      tags: ["Python", "机器学习", "K均值", "聚类", "无监督学习", "SSE", "周报"],
      words: 3100,
      readTime: 10,
    },
    {
      id: "week7-regression-tree-learning-review",
      href: "posts/week7-regression-tree-learning-review.html",
      title: "第七周学习复盘：让决策树也能预测连续数值",
      date: "2026-08-31",
      updated: "2026-08-31",
      category: "学习札记",
      excerpt: "复现回归树、预剪枝、后剪枝和模型树，用节点数量、拟合曲线与相关系数理解树模型怎样处理连续数值。",
      tags: ["Python", "机器学习", "回归树", "模型树", "剪枝", "决策树", "周报"],
      words: 3900,
      readTime: 13,
    },
    {
      id: "week6-regression-learning-review",
      href: "posts/week6-regression-learning-review.html",
      title: "第六周学习复盘：从一条直线开始理解回归",
      date: "2026-08-24",
      updated: "2026-08-24",
      category: "学习札记",
      excerpt: "复现标准线性回归、局部加权线性回归、岭回归和前向逐步回归，用真实运行结果理解 RSS、k、lambda 与交叉验证。",
      tags: ["Python", "机器学习", "回归", "线性回归", "岭回归", "交叉验证", "周报"],
      words: 4100,
      readTime: 14,
    },
    {
      id: "week5-adaboost-learning-review",
      href: "posts/week5-adaboost-learning-review.html",
      title: "第五周学习复盘：从一棵会犯错的树桩，到一群会纠错的分类器",
      date: "2026-08-16",
      updated: "2026-08-16",
      category: "学习札记",
      excerpt: "从单层决策树、样本权重和 alpha 加权投票出发，复现 AdaBoost 三轮训练、病马预测与 ROC-AUC，并记录尚待解决的问题。",
      tags: ["Python", "机器学习", "AdaBoost", "集成学习", "ROC", "AUC", "周报"],
      words: 6800,
      readTime: 22,
    },
    {
      id: "python-logistic-regression-sigmoid-classification",
      href: "posts/python-logistic-regression-sigmoid-classification.html",
      title: "从打分到概率：零基础学会 Logistic 回归与 Sigmoid 分类",
      date: "2026-08-11",
      updated: "2026-08-11",
      category: "Python 入门",
      excerpt: "结合《机器学习实战》第五章源码，图解 Sigmoid、决策边界、对数似然和梯度更新，并完成二维分类与病马生存预测。",
      tags: ["Python", "机器学习", "Logistic回归", "Sigmoid", "分类算法", "梯度下降", "数据分析"],
      words: 8100,
      readTime: 26,
      series: { id: "python-intro", name: "Python 入门", index: 13 },
    },
    {
      id: "python-naive-bayes-spam-filter",
      href: "posts/python-naive-bayes-spam-filter.html",
      title: "让单词自己投票：零基础学会朴素贝叶斯与垃圾邮件过滤",
      date: "2026-07-27",
      updated: "2026-07-27",
      category: "Python 入门",
      excerpt: "结合《机器学习实战》第四章源码，从词表、词袋和贝叶斯公式讲起，用50封真实邮件完成垃圾邮件分类。",
      tags: ["Python", "机器学习", "朴素贝叶斯", "文本分类", "算法", "数据分析"],
      words: 7600,
      readTime: 25,
      series: { id: "python-intro", name: "Python 入门", index: 12 },
    },
    {
      id: "python-decision-tree-beginner-guide",
      href: "posts/python-decision-tree-beginner-guide.html",
      title: "像玩猜谜一样做预测：零基础彻底学会决策树",
      date: "2026-07-26",
      updated: "2026-07-26",
      category: "Python 入门",
      excerpt: "从连续提问和基尼不纯度讲起，手算最佳切分，再用 Python 与 scikit-learn 完成训练、剪枝、可视化和评估。",
      tags: ["Python", "机器学习", "决策树", "算法", "数据分析"],
      words: 7200,
      readTime: 24,
      series: { id: "python-intro", name: "Python 入门", index: 11 },
    },
    {
      id: "python-knn-basic-algorithm",
      href: "posts/python-knn-basic-algorithm.html",
      title: "让邻居替你做决定：零基础学会 K 近邻算法（KNN）",
      date: "2026-07-22",
      updated: "2026-07-23",
      category: "Python 入门",
      excerpt: "从距离、邻居投票和 K 值讲起，手算一个分类案例，再用 NumPy 与 scikit-learn 完成可运行的 KNN 分类器。",
      tags: ["Python", "机器学习", "KNN", "算法", "数据分析"],
      words: 5600,
      readTime: 18,
      series: { id: "python-intro", name: "Python 入门", index: 10 },
    },
    {
      id: "python-tuple-basic",
      href: "posts/python-tuple-basic-usage.html",
      title: "Python数据容器-tuple",
      date: "2026-06-24",
      updated: "2026-06-24",
      category: "Python 入门",
      excerpt: "元组的定义、索引访问、切片访问、count 和 index 方法，以及用学生成绩单统计总分、平均分、各科成绩和优秀学生。",
      tags: ["Python", "基础", "元组", "数据容器"],
      words: 1320,
      readTime: 5,
      series: { id: "python-intro", name: "Python 入门", index: 9 },
    },
    {
      id: "python-string-container-basic",
      href: "posts/python-str-basic-operations.html",
      title: "数据容器 str 基本操作",
      date: "2026-06-17",
      updated: "2026-06-17",
      category: "Python 入门",
      excerpt: "字符串的索引、遍历、切片，以及 find、count、upper、lower、split、strip、replace、startswith 和邮箱格式验证示例。",
      tags: ["Python", "基础", "字符串", "数据容器"],
      words: 1380,
      readTime: 5,
      series: { id: "python-intro", name: "Python 入门", index: 8 },
    },
    {
      id: "python-list-basic",
      href: "posts/python-list-basic-usage.html",
      title: "数据容器 list 基本用法",
      date: "2026-05-28",
      updated: "2026-06-17",
      category: "Python 入门",
      excerpt: "列表的定义、元素访问、修改、删除、遍历、切片，以及 append、insert、extend、remove、pop、sort 等常用方法。",
      tags: ["Python", "基础", "列表", "数据容器"],
      words: 1640,
      readTime: 6,
      series: { id: "python-intro", name: "Python 入门", index: 7 },
    },
    {
      id: "python-if-elif-else",
      href: "posts/python-if-elif-else.html",
      title: "Python 中 if elif else 用法",
      date: "2026-05-17",
      updated: "2026-05-28",
      category: "Python 入门",
      excerpt: "if、elif、else 条件判断示例，包含分数判断、账号密码登录判断和正负数判断。",
      tags: ["Python", "基础", "条件判断", "if elif else"],
      words: 1180,
      readTime: 4,
      series: { id: "python-intro", name: "Python 入门", index: 6 },
    },
    {
      id: "python-operators",
      href: "posts/python-operators.html",
      title: "Python 中的运算符",
      date: "2026-04-30",
      updated: "2026-05-17",
      category: "Python 入门",
      excerpt: "加减乘除、整除、取余、幂运算，以及输入两个数计算和与差。",
      tags: ["Python", "基础", "运算符"],
      words: 920,
      readTime: 3,
      series: { id: "python-intro", name: "Python 入门", index: 5 },
    },
    {
      id: "python-input-output",
      href: "posts/python-input-and-output.html",
      title: "Python 中输入与输出",
      date: "2026-04-29",
      updated: "2026-04-30",
      category: "Python 入门",
      excerpt: "input() 获取用户输入，print() 与 f-string 输出格式化内容，包含取款与求和小例子。",
      tags: ["Python", "基础", "输入输出", "print"],
      words: 1020,
      readTime: 4,
      series: { id: "python-intro", name: "Python 入门", index: 4 },
    },
    {
      id: "python-string-definition",
      href: "posts/python-strings-definition-and-operations.html",
      title: "字符串的定义以及操作",
      date: "2026-04-28",
      updated: "2026-04-29",
      category: "Python 入门",
      excerpt: "常见数据类型、isinstance 检查、字符串三种定义方式、转义字符与格式化示例。",
      tags: ["Python", "基础", "字符串"],
      words: 1260,
      readTime: 5,
      series: { id: "python-intro", name: "Python 入门", index: 3 },
    },
    {
      id: "python-literals-variables",
      href: "posts/python-literals-and-variables.html",
      title: "Python 中的字面量及自变量",
      date: "2026-04-28",
      updated: "2026-04-28",
      category: "Python 入门",
      excerpt: "Python 是动态类型语言，一个变量可以存储不同类型的数据。",
      tags: ["Python", "基础", "变量", "字面量"],
      words: 830,
      readTime: 3,
      series: { id: "python-intro", name: "Python 入门", index: 2 },
    },
    {
      id: "llm-nlp-era-summary",
      href: "posts/llm-nlp-era-summary.html",
      title: "《大模型时代的自然语言处理: 挑战、机遇与发展文献》总结",
      date: "2026-04-26",
      updated: "2026-04-26",
      category: "论文笔记",
      excerpt: "梳理 LLM 对 NLP 任务范式、共性挑战、未来方向和具体应用场景的影响。",
      tags: ["LLM", "NLP", "论文笔记", "综述"],
      words: 3860,
      readTime: 13,
    },
    {
      id: "python-hello-world",
      href: "posts/first-post.html",
      title: "人生苦短，我用 Python",
      date: "2026-04-25",
      updated: "2026-04-26",
      indexable: false,
      category: "Python 入门",
      excerpt: "第一篇博客，记录从 0 开始学习 Python、项目结构和 Hello World 的足迹。",
      tags: ["Python", "入门"],
      words: 520,
      readTime: 2,
      series: { id: "python-intro", name: "Python 入门", index: 1 },
    },
    {
      id: "technical-notes-method",
      href: "posts/notes-template.html",
      title: "怎样写一篇未来自己也愿意重看的技术笔记",
      date: "2026-04-18",
      updated: "2026-04-18",
      category: "学习札记",
      excerpt: "整理一篇技术笔记时，如何让背景、过程、结论和复盘在未来仍然清楚可读。",
      tags: ["写作", "笔记", "方法论"],
      words: 760,
      readTime: 3,
    },
    {
      id: "life-fragments-writing",
      href: "posts/life-fragments.html",
      title: "把散乱的生活片段整理成可阅读的博客内容",
      date: "2026-04-10",
      updated: "2026-04-10",
      category: "日常",
      excerpt: "把零散生活观察整理成可阅读内容的示例，保留现场感，也补足结构。",
      tags: ["生活", "写作", "整理"],
      words: 680,
      readTime: 3,
    },
  ];
})();
