/* eslint-disable */
(() => {
  window.__BLOG_POSTS__ = [
    {
      href: "posts/python-str-basic-operations.html",
      title: "数据容器 str 基本操作",
      date: "2026-06-17",
      updated: "2026-06-17",
      category: "Python 入门",
      excerpt: "字符串的索引、遍历、切片，以及 find、count、upper、lower、split、strip、replace、startswith 和邮箱格式验证示例。",
      tags: ["Python", "基础", "字符串", "数据容器"],
      words: 1380,
      readTime: 5,
      series: { id: "python-intro", name: "Python 入门", index: 8 },
    },
    {
      href: "posts/python-list-basic-usage.html",
      title: "数据容器 list 基本用法",
      date: "2026-05-28",
      updated: "2026-06-17",
      category: "Python 入门",
      excerpt: "列表的定义、元素访问、修改、删除、遍历、切片，以及 append、insert、extend、remove、pop、sort 等常用方法。",
      tags: ["Python", "基础", "列表", "数据容器"],
      words: 1640,
      readTime: 6,
      series: { id: "python-intro", name: "Python 入门", index: 7 },
    },
    {
      href: "posts/python-if-elif-else.html",
      title: "Python 中 if elif else 用法",
      date: "2026-05-17",
      updated: "2026-05-28",
      category: "Python 入门",
      excerpt: "if、elif、else 条件判断示例，包含分数判断、账号密码登录判断和正负数判断。",
      tags: ["Python", "基础", "条件判断", "if elif else"],
      words: 1180,
      readTime: 4,
      series: { id: "python-intro", name: "Python 入门", index: 6 },
    },
    {
      href: "posts/python-operators.html",
      title: "Python 中的运算符",
      date: "2026-04-30",
      updated: "2026-05-17",
      category: "Python 入门",
      excerpt: "加减乘除、整除、取余、幂运算，以及输入两个数计算和与差。",
      tags: ["Python", "基础", "运算符"],
      words: 920,
      readTime: 3,
      series: { id: "python-intro", name: "Python 入门", index: 5 },
    },
    {
      href: "posts/python-input-and-output.html",
      title: "Python 中输入与输出",
      date: "2026-04-29",
      updated: "2026-04-30",
      category: "Python 入门",
      excerpt: "input() 获取用户输入，print() 与 f-string 输出格式化内容，包含取款与求和小例子。",
      tags: ["Python", "基础", "输入输出", "print"],
      words: 1020,
      readTime: 4,
      series: { id: "python-intro", name: "Python 入门", index: 4 },
    },
    {
      href: "posts/python-strings-definition-and-operations.html",
      title: "字符串的定义以及操作",
      date: "2026-04-28",
      updated: "2026-04-29",
      category: "Python 入门",
      excerpt: "常见数据类型、isinstance 检查、字符串三种定义方式、转义字符与格式化示例。",
      tags: ["Python", "基础", "字符串"],
      words: 1260,
      readTime: 5,
      series: { id: "python-intro", name: "Python 入门", index: 3 },
    },
    {
      href: "posts/python-literals-and-variables.html",
      title: "Python 中的字面量及自变量",
      date: "2026-04-28",
      updated: "2026-04-28",
      category: "Python 入门",
      excerpt: "Python 是动态类型语言，一个变量可以存储不同类型的数据。",
      tags: ["Python", "基础", "变量", "字面量"],
      words: 830,
      readTime: 3,
      series: { id: "python-intro", name: "Python 入门", index: 2 },
    },
    {
      href: "posts/llm-nlp-era-summary.html",
      title: "《大模型时代的自然语言处理: 挑战、机遇与发展文献》总结",
      date: "2026-04-26",
      updated: "2026-04-26",
      category: "论文笔记",
      excerpt: "梳理 LLM 对 NLP 任务范式、共性挑战、未来方向和具体应用场景的影响。",
      tags: ["LLM", "NLP", "论文笔记", "综述"],
      words: 3860,
      readTime: 13,
    },
    {
      href: "posts/first-post.html",
      title: "人生苦短，我用 Python",
      date: "2026-04-25",
      updated: "2026-04-26",
      indexable: false,
      category: "Python 入门",
      excerpt: "第一篇博客，记录从 0 开始学习 Python、项目结构和 Hello World 的足迹。",
      tags: ["Python", "入门"],
      words: 520,
      readTime: 2,
      series: { id: "python-intro", name: "Python 入门", index: 1 },
    },
    {
      href: "posts/notes-template.html",
      title: "怎样写一篇未来自己也愿意重看的技术笔记",
      date: "2026-04-18",
      updated: "2026-04-18",
      category: "学习札记",
      excerpt: "整理一篇技术笔记时，如何让背景、过程、结论和复盘在未来仍然清楚可读。",
      tags: ["写作", "笔记", "方法论"],
      words: 760,
      readTime: 3,
    },
    {
      href: "posts/life-fragments.html",
      title: "把散乱的生活片段整理成可阅读的博客内容",
      date: "2026-04-10",
      updated: "2026-04-10",
      category: "日常",
      excerpt: "把零散生活观察整理成可阅读内容的示例，保留现场感，也补足结构。",
      tags: ["生活", "写作", "整理"],
      words: 680,
      readTime: 3,
    },
  ];
})();
