"""Import a public NetEase playlist snapshot, preserving the complete song order.

Usage: python scripts/import-netease-playlist.py 2427750321
Re-run after changing the source playlist, then publish the updated snapshot.
"""
import argparse
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen

API_ORIGIN = "https://music.163.com"
BATCH_SIZE = 100
OUTPUT = Path(__file__).resolve().parents[1] / "music-playlist.js"


def fetch_json(path, parameters):
    request = Request(
        f"{API_ORIGIN}{path}?{urlencode(parameters)}",
        headers={"User-Agent": "Mozilla/5.0", "Referer": f"{API_ORIGIN}/"},
    )
    with urlopen(request, timeout=20) as response:
        result = json.load(response)
    if result.get("code") != 200:
        raise RuntimeError(f"NetEase request failed: {path}, code={result.get('code')}")
    return result


def fetch_songs(song_ids):
    result = fetch_json("/api/song/detail/", {"ids": json.dumps(song_ids)})
    return result["songs"]


def import_playlist(playlist_id):
    result = fetch_json("/api/v6/playlist/detail", {"id": playlist_id, "n": 1000})
    playlist = result["playlist"]
    song_ids = [track["id"] for track in playlist["trackIds"]]
    if len(song_ids) != playlist["trackCount"] or not song_ids:
        raise RuntimeError("Playlist IDs are incomplete or empty; existing snapshot was not changed.")
    batches = [song_ids[start:start + BATCH_SIZE] for start in range(0, len(song_ids), BATCH_SIZE)]
    with ThreadPoolExecutor(max_workers=4) as pool:
        songs = {song["id"]: song for batch in pool.map(fetch_songs, batches) for song in batch}
    missing = [song_id for song_id in song_ids if song_id not in songs]
    if missing:
        raise RuntimeError(f"Missing song details for {missing}; existing snapshot was not changed.")
    return {
        "id": playlist_id,
        "name": playlist["name"],
        "source": f"{API_ORIGIN}/playlist?id={playlist_id}",
        "tracks": [
            {
                "neteaseSongId": str(song_id),
                "title": songs[song_id]["name"],
                "artist": " / ".join(artist["name"] for artist in songs[song_id]["artists"]),
                "cover": songs[song_id]["album"]["picUrl"],
            }
            for song_id in song_ids
        ],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("playlist_id", type=int)
    arguments = parser.parse_args()
    snapshot = import_playlist(arguments.playlist_id)
    content = "// Generated by scripts/import-netease-playlist.py; public playlist snapshot.\n"
    content += "window.BLOG_MUSIC_PLAYLIST = " + json.dumps(snapshot, ensure_ascii=False, indent=2) + ";\n"
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Imported {len(snapshot['tracks'])} songs from playlist {snapshot['id']}.")


if __name__ == "__main__":
    main()
